/**
 * Copyright (c) 2026 River Tech. All rights reserved.
 */
import {
  Aperture,
  AudioLines,
  BookOpen,
  Calendar,
  Camera,
  Captions,
  CassetteTape,
  Clapperboard,
  Disc3,
  FileText,
  Film,
  Flag,
  Gavel,
  Globe,
  Handshake,
  Headphones,
  Image,
  Instagram,
  Landmark,
  Link,
  Mail,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  MicVocal,
  MonitorPlay,
  Music,
  Newspaper,
  Palette,
  PenTool,
  Phone,
  Play,
  Podcast,
  Radio,
  Scissors,
  Share2,
  Smartphone,
  Sparkles,
  Speaker,
  Star,
  Tv,
  Users,
  Video,
  Volume2,
  Youtube,
  type LucideIcon,
} from 'lucide-react';
import type { MediaTypeIcon } from './media-type-icon-catalog';

const ICONS: Record<MediaTypeIcon, LucideIcon> = {
  camera: Camera,
  film: Film,
  image: Image,
  mic: Mic,
  'message-square': MessageSquare,
  clapperboard: Clapperboard,
  newspaper: Newspaper,
  video: Video,
  music: Music,
  'file-text': FileText,
  podcast: Podcast,
  radio: Radio,
  headphones: Headphones,
  megaphone: Megaphone,
  tv: Tv,
  'monitor-play': MonitorPlay,
  play: Play,
  'volume-2': Volume2,
  speaker: Speaker,
  'disc-3': Disc3,
  'mic-vocal': MicVocal,
  'cassette-tape': CassetteTape,
  captions: Captions,
  'audio-lines': AudioLines,
  palette: Palette,
  'pen-tool': PenTool,
  aperture: Aperture,
  sparkles: Sparkles,
  youtube: Youtube,
  instagram: Instagram,
  'share-2': Share2,
  link: Link,
  globe: Globe,
  users: Users,
  calendar: Calendar,
  smartphone: Smartphone,
  landmark: Landmark,
  gavel: Gavel,
  handshake: Handshake,
  mail: Mail,
  phone: Phone,
  'message-circle': MessageCircle,
  'book-open': BookOpen,
  flag: Flag,
  star: Star,
  scissors: Scissors,
};

export function ContentTypeIcon({ icon, className }: { icon: MediaTypeIcon | string; className?: string }) {
  const Icon = ICONS[icon as MediaTypeIcon] ?? FileText;
  return <Icon className={className} aria-hidden />;
}
