/**
 * Copyright (c) 2026 River Tech. All rights reserved.
 */
import { type AppLocale, pickCopy } from '@/lib/locale';

const copy = {
  en: {
    title: 'Media',
    description: 'Shoot, edit, and publish the next piece.',
    empty: 'No media pieces yet. Add the first one.',
    emptyType: 'No {name} pieces yet. Add the first one.',
    emptyMonth: 'No media pieces this month.',
    emptyMonthType: 'No {name} pieces this month.',
    emptyWeek: 'No media pieces this week.',
    emptyWeekType: 'No {name} pieces this week.',
    emptyDay: 'No media pieces this day.',
    emptyDayType: 'No {name} pieces this day.',
    backToMedia: 'All media',
    calendarTab: 'Calendar',
    listTab: 'List',
    boardTab: 'Board',
    boardDrop: 'Drop a piece here.',
    boardMove: 'Move {name}',
    boardColumns: {
      edit: 'In edit',
      review: 'In review',
      post: 'Ready to post',
      closed: 'Closed',
    },
    today: 'Today',
    viewMonth: 'Month',
    viewWeek: 'Week',
    viewDay: 'Day',
    shoot: 'Shoot',
    publish: 'Publish',
    addOnDay: 'Add piece on {name}',
    weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    manage: 'Manage content',
    manageTitle: 'Content types',
    manageDescription: 'Add a type, edit it, or turn it off. Each type has an icon so the desk can spot it.',
    addType: 'Add type',
    addTypeTitle: 'Add content type',
    editTypeTitle: 'Edit content type',
    typeFormDescription: 'Name, short hint, and an icon.',
    typeNameLabel: 'Name',
    typeHintLabel: 'Hint',
    typeHintPlaceholder: 'Session stills',
    typeIconLabel: 'Icon',
    iconSearchPlaceholder: 'Search icons',
    iconSearchEmpty: 'No icons match. Try photo, mic, or video.',
    typeActive: 'Active',
    inactive: 'Inactive',
    deleteTypeTitle: 'Remove type',
    deleteTypeDescription: 'Remove {name} from the catalog?',
    typeCreated: 'Content type added.',
    typeUpdated: 'Content type updated.',
    typeDeleted: 'Content type removed.',
    add: 'Add project content',
    addTitle: 'Add project content',
    composeDescription: 'What it is, when it happens, and who has it.',
    typePickerLabel: 'Type of content',
    kpis: {
      in_edit: { label: 'In edit', hint: 'Not started through caption' },
      in_review: { label: 'In review', hint: 'Waiting on a reviewer' },
      ready_to_post: { label: 'Ready to post', hint: 'Ready or scheduled' },
      due_today: { label: 'Due today', hint: 'Shoot or publish is today' },
    },
    kpiEmpty: 'No pieces in this pile.',
    needsAttention: 'Needs attention',
    openMinute: '{count} min open',
    openHour: '{count} hr open',
    openDay: '1 day open',
    openDays: '{count} days open',
    editTitle: 'Edit media piece',
    formDescription: 'Update the piece, the dates, or who has it.',
    typeHints: {
      photo: 'Session stills',
      reels: 'Short video',
      graphics: 'Cards and posters',
      podcast: 'Audio episode',
      message: 'Written post',
    },
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    detailsLabel: 'Details',
    assignedLabel: 'Assigned',
    editorLabel: 'Editor',
    reviewerLabel: 'Reviewer',
    deployedLabel: 'Deployer',
    nameLabel: 'Name',
    typeLabel: 'Type of content',
    statusLabel: 'Status',
    personLabel: 'Person',
    personNone: '—',
    notAssigned: 'Not assigned',
    emptyField: 'Empty',
    whenLabel: 'When',
    whoLabel: 'Who',
    deployedFilter: 'Deployer',
    dateBoth: 'Both',
    personAnyone: 'Anyone',
    clearWhen: 'Clear date',
    clearWho: 'Clear person',
    dateToday: 'Today',
    dateYesterday: 'Yesterday',
    dateThisWeek: 'This week',
    dateLastWeek: 'Last week',
    dateLastMonth: 'Last month',
    dateCustom: 'Custom range',
    dateFrom: 'From',
    dateTo: 'To',
    captionLabel: 'Caption',
    subsLabel: 'Subs',
    episodeLabel: 'Episode',
    shootLabel: 'Shoot date',
    publishLabel: 'Publish date',
    linkLabel: 'Link',
    driveUrlLabel: 'Drive URL',
    fbUrlLabel: 'FB URL',
    openDrive: 'Open Drive',
    openFacebook: 'Open Facebook',
    linkPlaceholder: 'https://',
    detailsToggle: 'Caption, subs, and links',
    workSection: 'Copy and links',
    optionalLabel: 'Optional',
    statusFollowsDates: 'Follows the dates until you pick another.',
    loadError: 'Could not load media. Start the API with npm run dev:local.',
    created: 'Media piece added.',
    updated: 'Media piece updated.',
    deleted: 'Media piece removed.',
    delete: 'Delete',
    deleteTitle: 'Remove piece',
    deleteDescription: 'Remove {name} from the media board?',
    confirmDelete: 'Remove',
    view: 'View',
    edit: 'Edit',
    history: 'History',
    historyTitle: 'History',
    historyDescription: 'Who moved this piece, and when.',
    historyEmpty: 'No history yet.',
    historyCreated: '{name} added this piece.',
    historyUpdated: '{name} edited the piece.',
    historyStatus: '{name} changed status from {from} to {to}.',
    historyAssigned: '{name} assigned {role}: {people}.',
    historyUnassigned: '{name} removed {role}: {people}.',
    historyAssignedChanged: '{name} changed {role}: added {added}; removed {removed}.',
    historyComment: '{name} commented: {preview}',
    historyReaction: '{name} reacted {emoji} to a comment: {preview}',
    historyDeleted: '{name} deleted {title}.',
    commentsTitle: 'Comments',
    commentsDescription: 'Editors, reviewers, and deployers can leave a note.',
    commentPlaceholder: 'Leave a note…',
    commentPost: 'Comment',
    commentsEmpty: 'No comments yet.',
    commentPosted: 'Comment added.',
    reactLabel: 'React',
    openActions: 'Open actions',
    actions: 'Actions',
    types: {
      photo: 'Photo',
      reels: 'Reels',
      graphics: 'Graphics',
      podcast: 'Podcast',
      message: 'Message',
    },
    statuses: {
      not_started: 'Not started',
      editing: 'Editing',
      revision: 'Revision',
      caption: 'Caption',
      ready_for_review: 'Ready for review',
      under_review: 'Under review',
      ready_for_publish: 'Ready for publish',
      published: 'Published',
      not_published: 'Not published',
      scheduled_post: 'Scheduled post',
    },
  },
  fil: {
    title: 'Media',
    description: 'Shoot, i-edit, at i-publish ang susunod na piece.',
    empty: 'Wala pang media piece. Idagdag ang una.',
    emptyType: 'Wala pang {name} piece. Idagdag ang una.',
    emptyMonth: 'Walang media piece sa buwang ito.',
    emptyMonthType: 'Walang {name} piece sa buwang ito.',
    emptyWeek: 'Walang media piece sa linggong ito.',
    emptyWeekType: 'Walang {name} piece sa linggong ito.',
    emptyDay: 'Walang media piece sa araw na ito.',
    emptyDayType: 'Walang {name} piece sa araw na ito.',
    backToMedia: 'Lahat ng media',
    calendarTab: 'Calendar',
    listTab: 'List',
    boardTab: 'Board',
    boardDrop: 'I-drop ang piece dito.',
    boardMove: 'Ilipat si {name}',
    boardColumns: {
      edit: 'In edit',
      review: 'In review',
      post: 'Ready to post',
      closed: 'Closed',
    },
    today: 'Ngayon',
    viewMonth: 'Buwan',
    viewWeek: 'Linggo',
    viewDay: 'Araw',
    shoot: 'Shoot',
    publish: 'Publish',
    addOnDay: 'Magdagdag ng piece sa {name}',
    weekdays: ['Lin', 'Lun', 'Mar', 'Miy', 'Huw', 'Biy', 'Sab'],
    manage: 'Manage content',
    manageTitle: 'Content types',
    manageDescription: 'Magdagdag, i-edit, o i-off ang type. May icon ang bawat isa.',
    addType: 'Magdagdag ng type',
    addTypeTitle: 'Magdagdag ng content type',
    editTypeTitle: 'I-edit ang content type',
    typeFormDescription: 'Pangalan, maikling hint, at icon.',
    typeNameLabel: 'Pangalan',
    typeHintLabel: 'Hint',
    typeHintPlaceholder: 'Session stills',
    typeIconLabel: 'Icon',
    iconSearchPlaceholder: 'Maghanap ng icon',
    iconSearchEmpty: 'Walang tugmang icon. Subukan ang photo, mic, o video.',
    typeActive: 'Active',
    inactive: 'Inactive',
    deleteTypeTitle: 'Tanggalin ang type',
    deleteTypeDescription: 'Tanggalin si {name} sa catalog?',
    typeCreated: 'Naidagdag ang content type.',
    typeUpdated: 'Na-update ang content type.',
    typeDeleted: 'Tinanggal ang content type.',
    add: 'Add project content',
    addTitle: 'Add project content',
    composeDescription: 'Ano ito, kailan, at sino ang may hawak.',
    typePickerLabel: 'Uri ng content',
    kpis: {
      in_edit: { label: 'In edit', hint: 'Not started hanggang caption' },
      in_review: { label: 'In review', hint: 'Hinihintay ang reviewer' },
      ready_to_post: { label: 'Ready to post', hint: 'Ready o scheduled' },
      due_today: { label: 'Due today', hint: 'Shoot o publish ngayon' },
    },
    kpiEmpty: 'Walang piece sa pile na ito.',
    needsAttention: 'Kailangan ng pansin',
    openMinute: '{count} min nakabukas',
    openHour: '{count} oras nakabukas',
    openDay: '1 araw nakabukas',
    openDays: '{count} araw nakabukas',
    editTitle: 'I-edit ang media piece',
    formDescription: 'I-update ang piece, ang dates, o kung sino ang may hawak.',
    typeHints: {
      photo: 'Mga still ng session',
      reels: 'Maikling video',
      graphics: 'Cards at poster',
      podcast: 'Audio episode',
      message: 'Written post',
    },
    cancel: 'Kanselahin',
    close: 'Isara',
    save: 'I-save',
    detailsLabel: 'Details',
    assignedLabel: 'Assigned',
    editorLabel: 'Editor',
    reviewerLabel: 'Reviewer',
    deployedLabel: 'Deployer',
    nameLabel: 'Pangalan',
    typeLabel: 'Type of content',
    statusLabel: 'Status',
    personLabel: 'Tao',
    personNone: '—',
    notAssigned: 'Walang nakatalaga',
    emptyField: 'Empty',
    whenLabel: 'Kailan',
    whoLabel: 'Sino',
    deployedFilter: 'Deployer',
    dateBoth: 'Both',
    personAnyone: 'Anyone',
    clearWhen: 'I-clear ang date',
    clearWho: 'I-clear ang tao',
    dateToday: 'Ngayon',
    dateYesterday: 'Kahapon',
    dateThisWeek: 'This week',
    dateLastWeek: 'Last week',
    dateLastMonth: 'Last month',
    dateCustom: 'Custom range',
    dateFrom: 'Mula',
    dateTo: 'Hanggang',
    captionLabel: 'Caption',
    subsLabel: 'Subs',
    episodeLabel: 'Episode',
    shootLabel: 'Shoot date',
    publishLabel: 'Publish date',
    linkLabel: 'Link',
    driveUrlLabel: 'Drive URL',
    fbUrlLabel: 'FB URL',
    openDrive: 'Buksan ang Drive',
    openFacebook: 'Buksan ang Facebook',
    linkPlaceholder: 'https://',
    detailsToggle: 'Caption, subs, at links',
    workSection: 'Copy at links',
    optionalLabel: 'Optional',
    statusFollowsDates: 'Sumusunod sa dates hanggang palitan mo.',
    loadError: 'Hindi ma-load ang media. Patakbuhin ang API: npm run dev:local.',
    created: 'Naidagdag ang media piece.',
    updated: 'Na-update ang media piece.',
    deleted: 'Tinanggal ang media piece.',
    delete: 'Burahin',
    deleteTitle: 'Tanggalin ang piece',
    deleteDescription: 'Tanggalin si {name} sa media board?',
    confirmDelete: 'Tanggalin',
    view: 'Tingnan',
    edit: 'I-edit',
    history: 'History',
    historyTitle: 'History',
    historyDescription: 'Sino ang naggalaw sa piece, at kailan.',
    historyEmpty: 'Wala pang history.',
    historyCreated: 'Idinagdag ni {name} ang piece.',
    historyUpdated: 'In-edit ni {name} ang piece.',
    historyStatus: 'Pinalitan ni {name} ang status mula {from} papuntang {to}.',
    historyAssigned: 'Itinalaga ni {name} ang {role}: {people}.',
    historyUnassigned: 'Inalis ni {name} ang {role}: {people}.',
    historyAssignedChanged: 'Pinalitan ni {name} ang {role}: idinagdag {added}; inalis {removed}.',
    historyComment: 'Nag-comment si {name}: {preview}',
    historyReaction: 'Nag-react si {name} ng {emoji} sa comment: {preview}',
    historyDeleted: 'Tinanggal ni {name} si {title}.',
    commentsTitle: 'Comments',
    commentsDescription: 'Pwede mag-iwan ng note ang editor, reviewer, at deployer.',
    commentPlaceholder: 'Mag-iwan ng note…',
    commentPost: 'Comment',
    commentsEmpty: 'Wala pang comment.',
    commentPosted: 'Naidagdag ang comment.',
    reactLabel: 'React',
    openActions: 'Buksan ang kilos',
    actions: 'Kilos',
    types: {
      photo: 'Photo',
      reels: 'Reels',
      graphics: 'Graphics',
      podcast: 'Podcast',
      message: 'Message',
    },
    statuses: {
      not_started: 'Not started',
      editing: 'Editing',
      revision: 'Revision',
      caption: 'Caption',
      ready_for_review: 'Ready for review',
      under_review: 'Under review',
      ready_for_publish: 'Ready for publish',
      published: 'Published',
      not_published: 'Not published',
      scheduled_post: 'Scheduled post',
    },
  },
} as const;

export function getMediaCopy(locale?: AppLocale) {
  return pickCopy(copy, locale);
}

export function withPieceName(template: string, name: string) {
  return template.replaceAll('{name}', name);
}

export function formatMediaOpenAge(
  copy: { openMinute: string; openHour: string; openDay: string; openDays: string },
  duration: { value: number; unit: 'minute' | 'hour' | 'day' },
) {
  if (duration.unit === 'minute') return copy.openMinute.replaceAll('{count}', String(duration.value));
  if (duration.unit === 'hour') return copy.openHour.replaceAll('{count}', String(duration.value));
  if (duration.value === 1) return copy.openDay;
  return copy.openDays.replaceAll('{count}', String(duration.value));
}
