/**
 * Copyright (c) 2026 River Tech. All rights reserved.
 */
import { type AppLocale, pickCopy } from '@/lib/locale';

const copy = {
  en: {
    title: 'Las Piñas',
    description: 'Where open solicitation work sits.',
    loadError: 'Could not load analytics. Start the API with npm run dev:local.',
    empty: 'No open solicitations.',
    openSummary: (count: number) =>
      count === 1 ? '1 open solicitation across Las Piñas.' : `${count} open solicitations across Las Piñas.`,
    cards: {
      pendingReview: 'Pending for Review',
      forApproval: 'For Approval',
      eligible: 'Eligible',
      readyToClaim: 'Ready for Claim',
    },
    barangayLoad: 'Barangay load',
    barangayLoadHint: 'Darker means more open cases. Click a barangay for its list; click it again to show the whole map.',
    rankedLoad: 'Highest load',
    district1: 'District 1',
    district2: 'District 2',
    mapEmptySelect: 'Click a barangay to see its open solicitations.',
    mapEmptyBarangay: 'No open solicitations in this barangay.',
    openInQueue: 'Open in queue',
    showAll: 'Show all',
    openInBarangay: (count: number) => (count === 1 ? '1 open case' : `${count} open cases`),
    legendLow: 'Fewer',
    legendHigh: (max: number) => `${max}`,
    legendTitle: 'Open cases',
    pipelineMix: 'Pipeline',
    pipelineMixHint: 'Share by stage in the selected range.',
    typeMix: 'Type of solicit',
    typeMixHint: 'Share by type in the selected range.',
    pipelineMixIn: (barangay: string) => `Pipeline · ${barangay}`,
    typeMixIn: (barangay: string) => `Type of solicit · ${barangay}`,
    fundTitle: 'Solicitation fund',
    fundHint: 'Remaining is allotted minus claimed and ready for claim.',
    fundAllotted: 'Allotted',
    fundRemaining: 'Remaining',
    fundClaimed: 'Claimed',
    fundReady: 'Ready for Claim',
    fundOfAllotted: (allotted: string) => `of ${allotted} allotted`,
    fundOver: 'Over allotted',
    byType: 'By type',
    casesLabel: 'Cases',
    nav: {
      dashboard: 'Dashboard',
      solicitation: 'Solicitation',
      media: 'Media',
      legislative: 'Legislative',
      assistant: 'Assistant',
      users: 'Users',
      notifications: 'Notifications',
      activity: 'Activity',
    },
    sidebarShow: 'Show navigation',
    sidebarHide: 'Hide navigation',
    noBreakdown: 'No open cases yet.',
    briefingTitle: 'Where work sits',
    filterFrom: 'From',
    filterTo: 'To',
    filterStatus: 'Status',
    filterType: 'Type',
    filterAll: 'All',
    filterOpen: 'Open',
    dailyChart: 'Solicits per day',
    dailyChartIn: (barangay: string) => `Solicits per day · ${barangay}`,
    dailyChartHint: 'Filed each day, by type. Click a barangay to scope this chart.',
    dailyChartEmpty: 'No solicitations in this range.',
    solicitationTab: 'Solicitation',
    mediaTab: 'Media',
    assistantTab: 'Assistant',
    legislativeTab: 'Legislative',
    mediaDescription: 'Where production work sits.',
    mediaHint: 'Open work, who is holding it, and remaining this month.',
    mediaBoard: 'Open media',
    mediaEmpty: 'No media pieces yet.',
    mediaPipeline: 'Status mix',
    mediaPipelineHint: 'Share by actual production status.',
    mediaTypes: 'Type mix',
    mediaTypesHint: 'Share by type of content.',
    mediaWeekTitle: 'This week',
    mediaWeekShoot: 'Shoot dates',
    mediaWeekPublish: 'Publish dates',
    mediaMonthTitle: 'Closed this month',
    mediaOpenTitle: 'Still open',
    mediaOpenHint: 'Filter by status, sort by dates, and page through open work.',
    mediaOpenEmpty: 'Nothing is open.',
    mediaOpenFilteredEmpty: 'No open pieces match this status.',
    mediaOpenSort: 'Sort',
    mediaOpenSortOpenOldest: 'Open age · oldest',
    mediaOpenSortOpenNewest: 'Open age · newest',
    mediaOpenSortShootAsc: 'Shoot date · earliest',
    mediaOpenSortShootDesc: 'Shoot date · latest',
    mediaOpenSortPublishAsc: 'Publish date · earliest',
    mediaOpenSortPublishDesc: 'Publish date · latest',
    mediaOpenMore: (count: number) => `${count} more on the board`,
    mediaOpenCount: (count: number) => (count === 1 ? '1 open' : `${count} open`),
    mediaHoldingTitle: 'Who is holding work',
    mediaHoldingHint: 'Open load by editor, reviewer, and deployer. Assigned now — not a scorecard.',
    mediaHoldingEmpty: 'Nobody is assigned to open or recently closed work.',
    mediaUnassigned: 'Unassigned',
    mediaHoldingOpen: 'open',
    mediaHoldingClosed: 'closed this month',
    mediaHoldingOldest: 'Oldest open',
    mediaHoldingNone: '—',
    mediaRecentTitle: 'Recent activity',
    mediaRecentHint: 'Adds, edits, assigns, comments, reacts, and deletes — newest first.',
    mediaRecentEmpty: 'No media activity yet.',
    mediaMissingPiece: 'Removed piece',
    mediaProductivityTitle: 'Productivity',
    mediaProductivityHint: 'Pieces added in the range. Rings and mix use that window; burndown shows open load across the dates.',
    mediaRingClosed: 'Closed',
    mediaRingOpen: 'Still open',
    mediaRingAttention: 'Needs attention',
    mediaRingPublished: 'Published share',
    mediaRingDone: 'done',
    mediaRingPending: 'pending',
    mediaRingOpenNow: 'open now',
    mediaRingClosedScope: 'closed in range',
    mediaRingAttentionNow: 'flagged',
    mediaRingClear: 'clear',
    mediaRingPublishedNow: 'published',
    mediaRingNotPublished: 'not published',
    mediaDatesTitle: 'Dates in range',
    mediaClosedTitle: 'Closed in range',
    mediaRemainingTitle: 'Remaining open',
    mediaRemainingHint: 'Open pieces still on the board each day, reconstructed from live pieces — not a sprint plan.',
    mediaRemainingEmpty: 'No open pieces to plot.',
    mediaRemainingNow: 'still open',
  },
  fil: {
    title: 'Las Piñas',
    description: 'Saan nakaupo ang open na solicitation.',
    loadError: 'Hindi ma-load ang analytics. Patakbuhin ang API: npm run dev:local.',
    empty: 'Wala pang open na solicitation.',
    openSummary: (count: number) =>
      count === 1
        ? '1 open na solicitation sa Las Piñas.'
        : `${count} open na solicitation sa Las Piñas.`,
    cards: {
      pendingReview: 'Pending for Review',
      forApproval: 'For Approval',
      eligible: 'Eligible',
      readyToClaim: 'Ready for Claim',
    },
    barangayLoad: 'Barangay load',
    barangayLoadHint: 'Mas madilim, mas maraming open na case. I-click ang barangay para sa listahan; i-click ulit para sa buong mapa.',
    rankedLoad: 'Pinakamataas na load',
    district1: 'District 1',
    district2: 'District 2',
    mapEmptySelect: 'I-click ang barangay para makita ang open na solicitation.',
    mapEmptyBarangay: 'Wala pang open na solicitation sa barangay na ito.',
    openInQueue: 'Buksan sa queue',
    showAll: 'Ipakita lahat',
    openInBarangay: (count: number) => (count === 1 ? '1 open na case' : `${count} open na case`),
    legendLow: 'Mas kaunti',
    legendHigh: (max: number) => `${max}`,
    legendTitle: 'Open na case',
    pipelineMix: 'Pipeline',
    pipelineMixHint: 'Bahagi ayon sa stage sa selected range.',
    typeMix: 'Type of solicit',
    typeMixHint: 'Bahagi ayon sa uri sa selected range.',
    pipelineMixIn: (barangay: string) => `Pipeline · ${barangay}`,
    typeMixIn: (barangay: string) => `Type of solicit · ${barangay}`,
    fundTitle: 'Solicitation fund',
    fundHint: 'Remaining ay allotted minus claimed at ready for claim.',
    fundAllotted: 'Allotted',
    fundRemaining: 'Remaining',
    fundClaimed: 'Claimed',
    fundReady: 'Ready for Claim',
    fundOfAllotted: (allotted: string) => `ng ${allotted} allotted`,
    fundOver: 'Lampas sa allotted',
    byType: 'Ayon sa uri',
    casesLabel: 'Mga case',
    nav: {
      dashboard: 'Dashboard',
      solicitation: 'Solicitation',
      media: 'Media',
      legislative: 'Legislative',
      assistant: 'Assistant',
      users: 'Users',
      notifications: 'Abiso',
      activity: 'Activity',
    },
    sidebarShow: 'Ipakita ang navigation',
    sidebarHide: 'Itago ang navigation',
    noBreakdown: 'Wala pang open na case.',
    briefingTitle: 'Saan nakaupo ang trabaho',
    filterFrom: 'From',
    filterTo: 'To',
    filterStatus: 'Status',
    filterType: 'Type',
    filterAll: 'Lahat',
    filterOpen: 'Open',
    dailyChart: 'Solicit bawat araw',
    dailyChartIn: (barangay: string) => `Solicit bawat araw · ${barangay}`,
    dailyChartHint: 'Isinampa bawat araw, ayon sa uri. I-click ang barangay para i-scope ang chart.',
    dailyChartEmpty: 'Walang solicitation sa range na ito.',
    solicitationTab: 'Solicitation',
    mediaTab: 'Media',
    assistantTab: 'Assistant',
    legislativeTab: 'Legislative',
    mediaDescription: 'Saan nakaupo ang production.',
    mediaHint: 'Open na trabaho, sino ang may hawak, at natitira ngayong buwan.',
    mediaBoard: 'Buksan ang media',
    mediaEmpty: 'Wala pang media piece.',
    mediaPipeline: 'Status mix',
    mediaPipelineHint: 'Bahagi ayon sa totoong production status.',
    mediaTypes: 'Type mix',
    mediaTypesHint: 'Bahagi ayon sa type of content.',
    mediaWeekTitle: 'Linggong ito',
    mediaWeekShoot: 'Mga shoot date',
    mediaWeekPublish: 'Mga publish date',
    mediaMonthTitle: 'Closed ngayong buwan',
    mediaOpenTitle: 'Still open',
    mediaOpenHint: 'I-filter ayon sa status, i-sort ayon sa petsa, at i-page ang open na trabaho.',
    mediaOpenEmpty: 'Walang open.',
    mediaOpenFilteredEmpty: 'Walang open piece na tumutugma sa status na ito.',
    mediaOpenSort: 'Sort',
    mediaOpenSortOpenOldest: 'Open age · pinakamatanda',
    mediaOpenSortOpenNewest: 'Open age · pinakabago',
    mediaOpenSortShootAsc: 'Shoot date · pinaka-maaga',
    mediaOpenSortShootDesc: 'Shoot date · pinakahuli',
    mediaOpenSortPublishAsc: 'Publish date · pinaka-maaga',
    mediaOpenSortPublishDesc: 'Publish date · pinakahuli',
    mediaOpenMore: (count: number) => `${count} pa sa board`,
    mediaOpenCount: (count: number) => (count === 1 ? '1 open' : `${count} open`),
    mediaHoldingTitle: 'Sino ang may hawak',
    mediaHoldingHint: 'Open load ng editor, reviewer, at deployer. Assignment ngayon — hindi scorecard.',
    mediaHoldingEmpty: 'Walang naka-assign sa open o recently closed na trabaho.',
    mediaUnassigned: 'Unassigned',
    mediaHoldingOpen: 'open',
    mediaHoldingClosed: 'closed ngayong buwan',
    mediaHoldingOldest: 'Pinakamatandang open',
    mediaHoldingNone: '—',
    mediaRecentTitle: 'Recent activity',
    mediaRecentHint: 'Add, edit, assign, comment, react, at delete — pinakabago muna.',
    mediaRecentEmpty: 'Wala pang media activity.',
    mediaMissingPiece: 'Tinanggal na piece',
    mediaProductivityTitle: 'Productivity',
    mediaProductivityHint: 'Mga piece na idinagdag sa range. Ang rings at mix ay sa window na iyon; burndown ay open load sa mga petsa.',
    mediaRingClosed: 'Closed',
    mediaRingOpen: 'Still open',
    mediaRingAttention: 'Needs attention',
    mediaRingPublished: 'Published share',
    mediaRingDone: 'done',
    mediaRingPending: 'pending',
    mediaRingOpenNow: 'open ngayon',
    mediaRingClosedScope: 'closed sa range',
    mediaRingAttentionNow: 'flagged',
    mediaRingClear: 'clear',
    mediaRingPublishedNow: 'published',
    mediaRingNotPublished: 'not published',
    mediaDatesTitle: 'Mga petsa sa range',
    mediaClosedTitle: 'Closed sa range',
    mediaRemainingTitle: 'Natitirang open',
    mediaRemainingHint: 'Open pieces sa board bawat araw, mula sa live na pieces — hindi sprint plan.',
    mediaRemainingEmpty: 'Walang open piece na i-plot.',
    mediaRemainingNow: 'still open',
  },
} as const;

export function getDashboardCopy(locale?: AppLocale) {
  return pickCopy(copy, locale);
}
