/**
 * Copyright (c) 2026 River Tech. All rights reserved.
 */
import { type AppLocale, pickCopy } from '@/lib/locale';

const copy = {
  en: {
    title: 'Users',
    description: 'Add desk users, roles, and module access.',
    empty: 'No members yet. Add the first user.',
    add: 'Add User',
    invite: 'Add User',
    inviteTitle: 'Add User',
    inviteDescription: 'Create a desk login, role, and module access.',
    cancel: 'Cancel',
    usernameLabel: 'Username',
    firstNameLabel: 'First name',
    lastNameLabel: 'Last name',
    phoneLabel: 'Phone number',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    regeneratePassword: 'Generate new password',
    passwordHint: 'Share this once. The user should change it after first sign-in.',
    roleLabel: 'Role',
    managementLabel: 'Management access',
    ownerAccessNote: 'Owner has admin access to every module and every dashboard tab.',
    adminAccessNote: 'Admin users get dashboard tabs for each module where access is Admin.',
    accessNone: 'No access',
    userDetails: 'User details',
    permissionsColumn: 'Access',
    openActions: 'Open actions',
    loadError: 'Could not load users. Start the API with npm run dev:local.',
    created: 'User added.',
    createdWithPassword: (password: string) => `User added. Temporary password: ${password}`,
    updated: 'Access updated.',
    deleted: 'User removed.',
    delete: 'Delete',
    deleteTitle: 'Remove user',
    deleteDescription: 'Remove {name} from this desk? They will lose access.',
    confirmDelete: 'Remove',
    save: 'Save',
    edit: 'Edit',
    view: 'View',
    viewTitle: 'User profile',
    viewDescription: 'Desk login and module access for {name}.',
    editTitle: 'Edit user',
    editDescription: 'Update desk login, role, and module access for {name}.',
    resetPasswordLabel: 'New password',
    resetPasswordHint: 'Regenerate only when you need a new temporary password.',
    changeRole: 'Change role',
    changeRoleTitle: 'Change role',
    changeRoleDescription: 'Pick a new desk role for {name}.',
    actions: 'Actions',
    statusLabel: 'Status',
    allPermissions: 'All access',
    none: 'No module access',
    media: 'Media',
    solicitation: 'Solicitation',
    assistant: 'Assistant',
    legislative: 'Legislative',
    media_admin: 'Admin access',
    media_member: 'Member access',
    solicitation_admin: 'Admin access',
    solicitation_accountant: 'Accountant access',
    solicitation_reviewer: 'Reviewer access',
    assistant_admin: 'Admin access',
    assistant_assistant: 'Assistant access',
    legislative_admin: 'Admin access',
    legislative_member: 'Member access',
    roles: {
      owner: 'Owner',
      admin: 'Admin',
      assistant: 'Assistant',
      member: 'Member',
    },
    statuses: {
      active: 'Active',
      invited: 'Invited',
      disabled: 'Disabled',
    },
  },
  fil: {
    title: 'Users',
    description: 'Magdagdag ng desk user, role, at module access.',
    empty: 'Wala pang miyembro. Add the first user.',
    add: 'Add User',
    invite: 'Add User',
    inviteTitle: 'Add User',
    inviteDescription: 'Gumawa ng desk login, role, at module access.',
    cancel: 'Kanselahin',
    usernameLabel: 'Username',
    firstNameLabel: 'First name',
    lastNameLabel: 'Last name',
    phoneLabel: 'Phone number',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    regeneratePassword: 'Generate new password',
    passwordHint: 'I-share once. Palitan ng user pagkatapos ng unang sign-in.',
    roleLabel: 'Role',
    managementLabel: 'Management access',
    ownerAccessNote: 'Ang Owner ay may admin access sa lahat ng module at dashboard tab.',
    adminAccessNote: 'Ang Admin users ay may dashboard tab sa bawat module na may Admin access.',
    accessNone: 'No access',
    userDetails: 'User details',
    permissionsColumn: 'Access',
    openActions: 'Buksan ang kilos',
    loadError: 'Hindi ma-load ang users. Patakbuhin ang API: npm run dev:local.',
    created: 'Naidagdag ang user.',
    createdWithPassword: (password: string) => `Naidagdag ang user. Temporary password: ${password}`,
    updated: 'Na-update ang access.',
    deleted: 'Tinanggal ang user.',
    delete: 'Burahin',
    deleteTitle: 'Tanggalin ang user',
    deleteDescription: 'Tanggalin si {name} sa desk na ito? Mawawalan sila ng access.',
    confirmDelete: 'Tanggalin',
    save: 'I-save',
    edit: 'I-edit',
    view: 'Tingnan',
    viewTitle: 'User profile',
    viewDescription: 'Desk login at module access para kay {name}.',
    editTitle: 'I-edit ang user',
    editDescription: 'I-update ang desk login, role, at module access para kay {name}.',
    resetPasswordLabel: 'Bagong password',
    resetPasswordHint: 'I-regenerate lang kung kailangan ng bagong temporary password.',
    changeRole: 'Palitan ang role',
    changeRoleTitle: 'Palitan ang role',
    changeRoleDescription: 'Pumili ng bagong desk role para kay {name}.',
    actions: 'Kilos',
    statusLabel: 'Status',
    allPermissions: 'All access',
    none: 'No module access',
    media: 'Media',
    solicitation: 'Solicitation',
    assistant: 'Assistant',
    legislative: 'Legislative',
    media_admin: 'Admin access',
    media_member: 'Member access',
    solicitation_admin: 'Admin access',
    solicitation_accountant: 'Accountant access',
    solicitation_reviewer: 'Reviewer access',
    assistant_admin: 'Admin access',
    assistant_assistant: 'Assistant access',
    legislative_admin: 'Admin access',
    legislative_member: 'Member access',
    roles: {
      owner: 'Owner',
      admin: 'Admin',
      assistant: 'Assistant',
      member: 'Member',
    },
    statuses: {
      active: 'Active',
      invited: 'Invited',
      disabled: 'Disabled',
    },
  },
} as const;

export function getUsersCopy(locale?: AppLocale) {
  return pickCopy(copy, locale);
}

export function withMemberName(template: string, name: string) {
  return template.replaceAll('{name}', name);
}
