/**
 * Copyright (c) 2026 River Tech. All rights reserved.
 */
import { type AppLocale, pickCopy } from '@/lib/locale';

export const PUBLIC_STEP_IDS = ['write', 'desk', 'claim'] as const;
export type PublicStepId = (typeof PUBLIC_STEP_IDS)[number];

const copy = {
  en: {
    title: 'Solicitation',
    spiel: 'Help from the office. Free.',
    stepsTitle: 'Steps',
    steps: {
      write: 'Request',
      desk: 'Desk',
      claim: 'Claim',
    },
    stepPreviews: {
      write: 'Write your name.',
      desk: 'Bring papers. Desk photographs them, then says yes or no.',
      claim: 'Receive and sign.',
    },
    requestTab: 'Request',
    claimTab: 'Claim',
    requestHint: 'Ask for help',
    claimHint: 'I will receive',
    requestLead: 'Write your name. Desk takes the papers.',
    claimLead: 'Show your code.',
    backToPortal: 'Home',
    requestSuccess: 'Request sent. Pending for Review.',
    requestSuccessBody: 'Bring your papers to the desk. Staff will photograph them.',
    receiptTitle: 'Bring these',
    receiptBody: 'Desk will look. Code comes after yes.',
    newRequest: 'Request again',
    claimSuccess: 'Yes. Desk can give the help.',
    staffLink: 'Staff',
    papersTab: 'Papers',
    papersLead: 'Upload a photo of each paper.',
    papersHaveThis: 'I have this',
    fillDemoPapers: 'Fill demo papers',
    papersUpload: 'Add photo',
    papersChange: 'Change photo',
    papersSubmit: 'Submit papers',
    papersDone: 'Desk will look. Code comes after yes.',
    papersNeedAll: 'Upload every paper.',
    papersPhotoBadType: 'Use a photo of the paper.',
    papersPhotoDecodeFailed: 'Could not read that photo. Take it again in good light.',
    papersPhotoTooLarge: 'Photo is too large. Take a closer picture of the paper only.',
    papersMissing: 'Request not found. Start a request first.',
    papersClosed: 'Desk already has these papers.',
    controlHint: 'Save this number. Use it to claim.',
    papersLoadError: 'Could not load the papers. Start the API with npm run dev:local.',
    requirementLabels: {
      'valid-id': 'Valid government ID',
      'medical-certificate': 'Medical certificate',
      'hospital-bill': 'Hospital bill or prescription',
      'death-certificate': 'Death certificate',
      'funeral-contract': 'Funeral contract or statement of account',
      enrollment: 'Enrollment or registration form',
      assessment: 'School assessment or billing',
      'event-letter': 'Invitation or event letter',
      'need-proof': 'Proof of need or bill',
      'request-note': 'Short note of the daily need',
    },
  },
  fil: {
    title: 'Solicitation',
    spiel: 'Tulong mula sa opisina. Libre.',
    stepsTitle: 'Hakbang',
    steps: {
      write: 'Request',
      desk: 'Desk',
      claim: 'Claim',
    },
    stepPreviews: {
      write: 'Isulat ang pangalan.',
      desk: 'Dalhin ang papeles. Desk ang mag-upload, tapos oo o hindi.',
      claim: 'Tanggapin at pumirma.',
    },
    requestTab: 'Request',
    claimTab: 'Claim',
    requestHint: 'Humiling ng tulong',
    claimHint: 'Tatanggap ako',
    requestLead: 'Isulat ang pangalan. Desk ang mag-upload ng papeles.',
    claimLead: 'Ipakita ang code.',
    backToPortal: 'Uwi',
    requestSuccess: 'Naisumite. Pending for Review.',
    requestSuccessBody: 'Dalhin ang papeles sa desk. Staff ang mag-upload ng larawan.',
    receiptTitle: 'Dalhin ito',
    receiptBody: 'Titingnan ng desk. Code pagkatapos ng oo.',
    newRequest: 'Request ulit',
    claimSuccess: 'Oo. Puwede nang ibigay ng desk.',
    staffLink: 'Staff',
    papersTab: 'Papeles',
    papersLead: 'Mag-upload ng larawan ng bawat papeles.',
    papersHaveThis: 'May dala ako',
    fillDemoPapers: 'I-fill ang demo papeles',
    papersUpload: 'Lagay ang larawan',
    papersChange: 'Palitan ang larawan',
    papersSubmit: 'I-submit ang papeles',
    papersDone: 'Titingnan ng desk. Code pagkatapos ng oo.',
    papersNeedAll: 'I-upload ang bawat papeles.',
    papersPhotoBadType: 'Gumamit ng larawan ng papeles.',
    papersPhotoDecodeFailed: 'Hindi mabasa ang larawan. Kunin ulit sa maliwanag.',
    papersPhotoTooLarge: 'Masyadong malaki. Kunin ulit ang papeles nang mas malapit.',
    papersMissing: 'Walang request. Mag-request muna.',
    papersClosed: 'Nasa desk na ang papeles.',
    controlHint: 'I-save ang number. Gamitin sa claim.',
    papersLoadError: 'Hindi ma-load ang papeles. I-start ang API: npm run dev:local.',
    requirementLabels: {
      'valid-id': 'Valid government ID',
      'medical-certificate': 'Medical certificate',
      'hospital-bill': 'Hospital bill o reseta',
      'death-certificate': 'Death certificate',
      'funeral-contract': 'Funeral contract o statement of account',
      enrollment: 'Enrollment o registration form',
      assessment: 'School assessment o billing',
      'event-letter': 'Invitation o event letter',
      'need-proof': 'Proof of need o bill',
      'request-note': 'Maikling note ng daily need',
    },
  },
} as const;

export function getPublicSolicitationCopy(locale?: AppLocale) {
  return pickCopy(copy, locale);
}
