/**
 * Copyright (c) 2026 River Tech. All rights reserved.
 */
import { type AppLocale, pickCopy } from '@/lib/locale';

const copy = {
  en: {
    title: 'Solicitation',
    description: 'Open a case. Review papers. Decide.',
    empty: 'No solicitations yet.',
    emptyArchived: 'No claimed cases.',
    queueTab: 'Queue',
    searchPlaceholder: 'Name or control number',
    detailsLabel: 'Details',
    requestedDateLabel: 'Requested',
    openForMinute: (count: number) => (count === 1 ? '1 min open' : `${count} min open`),
    openForHour: (count: number) => (count === 1 ? '1 hr open' : `${count} hr open`),
    openForDay: (count: number) => (count === 1 ? '1 day open' : `${count} days open`),
    assignColumnLabel: 'Assign Reviewer / Accountant',
    actionLabel: 'Action',
    viewDetails: 'View details',
    unassigned: '—',
    statusLabel: 'Status',
    archived: 'Archived',
    kindFilter: 'Type',
    assignToFilter: 'Assign to',
    forBeneficiary: 'For',
    sameAsRequester: 'Same as the requestor',
    sameAsBeneficiary: 'Requestor is the beneficiary',
    fulfilled: 'Fulfilled',
    requirementNote: 'Note',
    requirementNoteHint: 'What you checked, or what is still missing.',
    cooldownShort: '3 mo.',
    nextActions: {
      under_review: 'Pending for Review',
      pending_validation: 'For Approval',
      rejected: 'Not Eligible',
      eligible: 'Eligible',
      ready_to_claim: 'Ready for Claim',
      claimed: 'Claimed',
    },
    add: 'Request solicitation',
    nameLabel: 'Requester',
    fullNameLabel: 'Full name',
    beneficiaryLabel: 'Beneficiary',
    beneficiaryHint: 'Who the help is for.',
    beneficiaryRequired: 'Write the beneficiary first name and surname.',
    beneficiaryRelationLabel: 'Relation to the beneficiary',
    beneficiaryRelationPlaceholder: 'Select relation',
    beneficiaryRelationRequired: 'Choose how you are related to the beneficiary.',
    beneficiaryRelationOtherLabel: 'Specify the relation',
    beneficiaryRelationOtherRequired: 'Write what the relation is.',
    beneficiaryRelations: {
      spouse: 'Spouse',
      parent: 'Parent',
      child: 'Child',
      sibling: 'Sibling',
      relative: 'Relative',
      guardian: 'Guardian',
      other: 'Others',
    },
    requesterIsBeneficiary: 'I am the beneficiary',
    suffixLabel: 'Suffix',
    suffixNone: 'None',
    firstNameLabel: 'First name',
    middleNameLabel: 'Middle name',
    noMiddleName: "I don't have a middle name",
    middleNameRequired: 'Write the middle name, or tick that there is none.',
    fillDemo: 'Fill demo request',
    lastNameLabel: 'Surname',
    addressLabel: 'Address',
    buildingLabel: 'Bldg / Blk / Lot',
    streetLabel: 'Street',
    subdivisionLabel: 'Subdivision / village',
    barangayLabel: 'Barangay',
    contactLabel: 'Contact',
    mobileLabel: 'Mobile',
    telephoneLabel: 'Home / telephone',
    emailLabel: 'Email',
    idSectionLabel: 'ID with address',
    idSectionHint: 'Pick the ID. Photo of the front and the back. Write what you see.',
    idTypeLabel: 'Type of ID',
    idLabel: 'ID number',
    idPhotoLabel: 'Photo of ID',
    idPhotoFrontLabel: 'Front',
    idPhotoBackLabel: 'Back',
    idPhotoHint: 'Both sides. Address is often on the back. Write the name and ID number.',
    idPhotoRequired: 'Need the front and the back of the ID.',
    scanId: 'Scan ID',
    scanHint: 'Fit the ID inside the box.',
    scanHintFront: 'Fit the front of the ID inside the box.',
    scanHintBack: 'Fit the back of the ID inside the box.',
    snapId: 'Take photo',
    closeScan: 'Close',
    galleryId: 'Add photo',
    cameraDenied: 'Camera is closed. Pick a photo instead.',
    readingId: 'Reading the ID…',
    idPhotoSaved: 'Photo saved. Write the name and ID number.',
    idPhotoSavedBack: 'Back saved.',
    idPhotoBadType: 'Use a photo of the ID.',
    idPhotoDecodeFailed: 'Could not read that photo. Take it again in good light.',
    idPhotoTooLarge: 'Photo is too large. Take a closer picture of the ID only.',
    idReadOk: 'Copied what we could read. Check if it is right.',
    idReadWeak: 'Could not read the ID. Hold it closer and try again, or write it.',
    barangayRequired: 'Pick a barangay.',
    idTypes: {
      philsys: 'PhilSys',
      drivers_license: "Driver's license",
      umid: 'UMID',
      voters: 'Voter',
      postal: 'Postal',
      barangay_id: 'Barangay ID',
    },
    kindLabel: 'Type of Solicitation',
    notesLabel: 'Reason',
    addressRequired: 'Write the address and pick a barangay.',
    reasonRequired: 'Write the reason.',
    relativesLabel: 'First family',
    relativeNameLabel: 'Relative name',
    relationLabel: 'Relation',
    addRelative: 'Add relative',
    requirementsLabel: 'Requirements',
    requirementsHint: 'Photograph each paper here. The requestor does not upload.',
    submitted: 'Submitted',
    validated: 'Validated',
    noPaperPhoto: 'No photo uploaded yet.',
    paperUpload: 'Add photo',
    paperChange: 'Change photo',
    paperPhotoBadType: 'Use a photo of the paper.',
    paperPhotoDecodeFailed: 'Could not read that photo. Take it again in good light.',
    paperPhotoTooLarge: 'Photo is too large. Take a closer picture of the paper only.',
    controlLabel: 'Control number',
    claimantLabel: 'Claimant name',
    claimPhotoLabel: 'Receive photo',
    acknowledgeLabel: 'I received the solicit',
    flagsLabel: 'Flags',
    caseTab: 'Case',
    fullDetails: 'Full details',
    papersInLabel: 'Papers in',
    nextLabel: 'Next',
    flagsNone: 'None',
    copyNumber: 'Copy',
    copied: 'Copied',
    deskToolsLabel: 'Desk tools',
    dueDiligenceLabel: 'Person check',
    dueDiligenceEmpty: 'No matching names above the confidence line.',
    dueDiligenceLoadError: 'Could not load matches.',
    triageTab: 'Triage',
    solicitHistoryTab: 'Solicit history',
    relativeTab: 'Relative',
    triageEmpty: 'No other names to check.',
    relativeEmpty: 'No tagged relatives.',
    confidenceLabel: 'Confidence',
    requestorRole: 'Requestor',
    beneficiaryRole: 'Beneficiary',
    bothRoles: 'Requestor and beneficiary',
    dateRequested: 'Date requested',
    dateReceived: 'Date received',
    samePersonTag: 'Same person',
    tagRelative: 'Tag relative',
    taggedRelative: 'Tagged relative',
    relativeTagged: 'Tagged as a relative.',
    recordsLabel: 'Solicit records',
    recordsEmpty: 'No earlier solicit records.',
    historyEmpty: 'No earlier cases for this person.',
    logsLabel: 'Logs',
    logsEmpty: 'No logs for this case yet.',
    loadError: 'Could not load solicitations. Start the API with npm run dev:local.',
    created: 'Solicitation requested. Issue the listed requirements.',
    updated: 'Requirements updated.',
    reviewed: 'Sent for validate.',
    approved: 'Eligible.',
    rejected: 'Solicitation rejected.',
    claimed: 'Solicit received and complete.',
    review: 'Review',
    validate: 'Validate',
    markComplete: 'Send for validate',
    approve: 'Eligible',
    markReady: 'Ready for Claim',
    markedReady: 'Funds are ready to claim.',
    override: 'Override eligible',
    reject: 'Not Eligible',
    rejectReasonLabel: 'Reject feedback',
    rejectReasonNeeded: 'Write why, and how they can fix it.',
    findingLabel: 'Reviewer finding',
    findingHint: 'Recommendation for admin. The requestor sees this only if you mark Not Eligible.',
    findingNoteLabel: 'Reviewer note',
    findingStatusLabel: 'Next status',
    findingStatusKeep: 'Keep current status',
    adminFindingLabel: 'Admin finding',
    adminFindingHint: 'Overall decision after the reviewer finding.',
    adminDecisionLabel: 'Overall decision',
    adminFindingNoteLabel: 'Admin note',
    adminDecisionLocked: 'Overall decision is available after the reviewer sends this for approval.',
    adminDecisionPending: 'Not yet decided',
    adminFindingNoteNeeded: 'Write why this is Not Eligible. The requestor will see it.',
    accountantIssueLabel: 'Accountant issue',
    accountantIssueHint: 'Remarks and the amount to provide. Set this after Eligible.',
    accountantIssueLocked: 'Amount is set after Eligible.',
    accountantNoteLabel: 'Remarks',
    fundAmountLabel: 'Amount',
    fundAmountNeeded: 'Set the amount before Ready for Claim.',
    findingActorEmpty: 'Not yet recorded.',
    attentionLabel: 'Attention',
    attentionHint: 'Mark if this case is special, odd, or needs a hand-off note.',
    attentionMarks: {
      special: 'Special',
      odd: 'Odd',
      conflict: 'Desk related to requestor',
      government_event: 'Government event',
    },
    findingSaved: 'Finding saved.',
    saveFinding: 'Save finding',
    findingNoteNeeded: 'Write why this is Not Eligible. The requestor will see it.',
    rejectLockedHint: 'After you save, Not Eligible cannot be overridden.',
    rejectConfirmTitle: 'Save as Not Eligible?',
    rejectConfirmBody: 'This decision cannot be overridden. The requestor will see the note you wrote.',
    rejectConfirm: 'Save as Not Eligible',
    rejectConfirmCancel: 'Cancel',
    claim: 'Claim',
    open: 'Open',
    saveRequirements: 'Save requirements',
    assignLabel: 'Assign',
    reviewerLabel: 'Reviewer',
    accountantLabel: 'Accountant',
    assignSave: 'Save assignment',
    assigned: 'Assignment saved.',
    missingLabel: 'Ask for papers',
    missingNoteLabel: 'What is missing',
    extraPaperLabel: 'Add another paper',
    escalateLabel: 'Ask admin',
    escalateNoteLabel: 'Why admin should look',
    expedite: 'Expedite',
    flagRequest: 'Flag request',
    flagRequester: 'Flag requestor',
    flagBeneficiary: 'Flag beneficiary',
    historyLabel: 'History',
    report: 'Generate report',
    reportExcel: 'Excel workbook',
    reportCsv: 'CSV',
    reportPdf: 'PDF statement',
    reportError: 'Could not generate the report.',
    cooldownRule: '3-month rule: this person already has a solicitation.',
    relativeFlag: 'First-family match',
    suspiciousFlag: 'Suspicious',
    claimHint: 'Control number plus the requester name, a receive photo, and an acknowledgement.',
    kinds: {
      burial: 'Burial',
      education: 'Educational',
      medical: 'Medical',
      events: 'Events',
      financial: 'Financial',
      daily: 'Daily',
    },
    statuses: {
      under_review: 'Pending for Review',
      pending_validation: 'For Approval',
      rejected: 'Not Eligible',
      eligible: 'Eligible',
      ready_to_claim: 'Ready for Claim',
      claimed: 'Claimed',
    },
    relations: {
      spouse: 'Spouse',
      parent: 'Parent',
      child: 'Child',
      sibling: 'Sibling',
    },
  },
  fil: {
    title: 'Solicitation',
    description: 'Buksan ang case. Suriin ang papeles. Magdesisyon.',
    empty: 'Wala pang solicitation.',
    emptyArchived: 'Wala pang naka-claim.',
    queueTab: 'Queue',
    searchPlaceholder: 'Pangalan o control number',
    detailsLabel: 'Detalye',
    requestedDateLabel: 'Requested',
    openForMinute: (count: number) => (count === 1 ? '1 min open' : `${count} min open`),
    openForHour: (count: number) => (count === 1 ? '1 hr open' : `${count} hr open`),
    openForDay: (count: number) => (count === 1 ? '1 day open' : `${count} days open`),
    assignColumnLabel: 'Assign Reviewer / Accountant',
    actionLabel: 'Aksyon',
    viewDetails: 'Tingnan ang detalye',
    unassigned: '—',
    statusLabel: 'Status',
    archived: 'Archived',
    kindFilter: 'Uri',
    assignToFilter: 'Assign to',
    forBeneficiary: 'Para kay',
    sameAsRequester: 'Pareho sa requestor',
    sameAsBeneficiary: 'Ang requestor ang beneficiary',
    fulfilled: 'Natupad',
    requirementNote: 'Note',
    requirementNoteHint: 'Ano ang natingnan, o ano pa ang kulang.',
    cooldownShort: '3 buwan',
    nextActions: {
      under_review: 'Pending for Review',
      pending_validation: 'For Approval',
      rejected: 'Not Eligible',
      eligible: 'Eligible',
      ready_to_claim: 'Ready for Claim',
      claimed: 'Claimed',
    },
    add: 'Mag-request ng solicitation',
    nameLabel: 'Pangalan',
    fullNameLabel: 'Buong pangalan',
    beneficiaryLabel: 'Beneficiary',
    beneficiaryHint: 'Sino ang tutulungan.',
    beneficiaryRequired: 'Isulat ang first name at surname ng beneficiary.',
    beneficiaryRelationLabel: 'Relasyon sa beneficiary',
    beneficiaryRelationPlaceholder: 'Piliin ang relasyon',
    beneficiaryRelationRequired: 'Piliin ang relasyon sa beneficiary.',
    beneficiaryRelationOtherLabel: 'Tukuyin ang relasyon',
    beneficiaryRelationOtherRequired: 'Isulat kung anong relasyon.',
    beneficiaryRelations: {
      spouse: 'Asawa',
      parent: 'Magulang',
      child: 'Anak',
      sibling: 'Kapatid',
      relative: 'Kamag-anak',
      guardian: 'Tagapag-alaga',
      other: 'Iba pa',
    },
    requesterIsBeneficiary: 'Ako ang beneficiary',
    suffixLabel: 'Suffix',
    suffixNone: 'Wala',
    firstNameLabel: 'First name',
    middleNameLabel: 'Middle name',
    noMiddleName: 'Wala akong middle name',
    middleNameRequired: 'Isulat ang middle name, o i-tick na wala.',
    fillDemo: 'I-fill ang demo request',
    lastNameLabel: 'Surname',
    addressLabel: 'Address',
    buildingLabel: 'Bldg / Blk / Lot',
    streetLabel: 'Street',
    subdivisionLabel: 'Subdivision / village',
    barangayLabel: 'Barangay',
    contactLabel: 'Contact',
    mobileLabel: 'Mobile',
    telephoneLabel: 'Home / telephone',
    emailLabel: 'Email',
    idSectionLabel: 'ID na may address',
    idSectionHint: 'Piliin ang ID. Larawan ng harap at likod. Isulat ang nakikita.',
    idTypeLabel: 'Uri ng ID',
    idLabel: 'ID number',
    idPhotoLabel: 'Larawan ng ID',
    idPhotoFrontLabel: 'Harap',
    idPhotoBackLabel: 'Likod',
    idPhotoHint: 'Dalawang side. Madalas nasa likod ang address. Isulat ang pangalan at ID number.',
    idPhotoRequired: 'Kailangan ang harap at likod ng ID.',
    scanId: 'I-scan ang ID',
    scanHint: 'Ilagay ang ID sa loob ng box.',
    scanHintFront: 'Ilagay ang harap ng ID sa loob ng box.',
    scanHintBack: 'Ilagay ang likod ng ID sa loob ng box.',
    snapId: 'Kunin',
    closeScan: 'Isara',
    galleryId: 'Lagay ang larawan',
    cameraDenied: 'Hindi mabuksan ang camera. Pumili ng larawan.',
    readingId: 'Binabasa ang ID…',
    idPhotoSaved: 'Nailagay ang larawan. Isulat ang pangalan at ID number.',
    idPhotoSavedBack: 'Nailagay ang likod.',
    idPhotoBadType: 'Gumamit ng larawan ng ID.',
    idPhotoDecodeFailed: 'Hindi mabasa ang larawan. Kunin ulit sa maliwanag.',
    idPhotoTooLarge: 'Masyadong malaki. Kunin ulit ang ID nang mas malapit.',
    idReadOk: 'Nasulat ang nabasa. Tingnan kung tama.',
    idReadWeak: 'Hindi mabasa ang ID. Ilapit at ulitin, o isulat.',
    barangayRequired: 'Pumili ng barangay.',
    idTypes: {
      philsys: 'PhilSys',
      drivers_license: "Driver's license",
      umid: 'UMID',
      voters: 'Voter',
      postal: 'Postal',
      barangay_id: 'Barangay ID',
    },
    kindLabel: 'Uri ng Solicitation',
    notesLabel: 'Reason',
    addressRequired: 'Isulat ang address at pumili ng barangay.',
    reasonRequired: 'Isulat ang reason.',
    relativesLabel: 'Unang pamilya',
    relativeNameLabel: 'Pangalan ng kamag-anak',
    relationLabel: 'Relasyon',
    addRelative: 'Dagdagan ang kamag-anak',
    requirementsLabel: 'Requirements',
    requirementsHint: 'I-upload ang larawan dito. Hindi nag-u-upload ang requestor.',
    submitted: 'Naisumite',
    validated: 'Na-validate',
    noPaperPhoto: 'Wala pang larawan.',
    paperUpload: 'Lagay ang larawan',
    paperChange: 'Palitan ang larawan',
    paperPhotoBadType: 'Gumamit ng larawan ng papeles.',
    paperPhotoDecodeFailed: 'Hindi mabasa ang larawan. Kunin ulit sa maliwanag.',
    paperPhotoTooLarge: 'Masyadong malaki. Kunin ulit ang papeles nang mas malapit.',
    controlLabel: 'Control number',
    claimantLabel: 'Pangalan ng claimant',
    claimPhotoLabel: 'Larawan ng receive',
    acknowledgeLabel: 'Natanggap ko ang solicit',
    flagsLabel: 'Flags',
    caseTab: 'Case',
    fullDetails: 'Buong detalye',
    papersInLabel: 'Papeles',
    nextLabel: 'Susunod',
    flagsNone: 'Wala',
    copyNumber: 'Kopyahin',
    copied: 'Nakopya',
    deskToolsLabel: 'Mga tool ng desk',
    dueDiligenceLabel: 'Person check',
    dueDiligenceEmpty: 'Walang tumugmang pangalan sa confidence line.',
    dueDiligenceLoadError: 'Hindi ma-load ang mga match.',
    triageTab: 'Triage',
    solicitHistoryTab: 'Solicit history',
    relativeTab: 'Relative',
    triageEmpty: 'Walang ibang pangalan na susuriin.',
    relativeEmpty: 'Walang naka-tag na kamag-anak.',
    confidenceLabel: 'Confidence',
    requestorRole: 'Requestor',
    beneficiaryRole: 'Beneficiary',
    bothRoles: 'Requestor at beneficiary',
    dateRequested: 'Date requested',
    dateReceived: 'Date received',
    samePersonTag: 'Same person',
    tagRelative: 'I-tag na kamag-anak',
    taggedRelative: 'Naka-tag na kamag-anak',
    relativeTagged: 'Naka-tag na kamag-anak.',
    recordsLabel: 'Mga solicit record',
    recordsEmpty: 'Wala pang naunang solicit record.',
    historyEmpty: 'Wala pang naunang case para sa taong ito.',
    logsLabel: 'Logs',
    logsEmpty: 'Wala pang log para sa case na ito.',
    loadError: 'Hindi ma-load ang solicitation. Patakbuhin ang API: npm run dev:local.',
    created: 'Na-request ang solicitation. Ibigay ang requirements.',
    updated: 'Na-update ang requirements.',
    reviewed: 'Naipadala para i-validate.',
    approved: 'Eligible.',
    rejected: 'Tinanggihan ang solicitation.',
    claimed: 'Natanggap at tapos na ang solicit.',
    review: 'Review',
    validate: 'I-validate',
    markComplete: 'Ipadala para i-validate',
    approve: 'Eligible',
    markReady: 'Ready for Claim',
    markedReady: 'Handa na ang pondo para i-claim.',
    override: 'I-override ang eligible',
    reject: 'Not Eligible',
    rejectReasonLabel: 'Feedback sa reject',
    rejectReasonNeeded: 'Isulat kung bakit, at paano maaayos.',
    findingLabel: 'Reviewer finding',
    findingHint: 'Rekomendasyon para sa admin. Makikita ng requestor kung Not Eligible.',
    findingNoteLabel: 'Note ng reviewer',
    findingStatusLabel: 'Susunod na status',
    findingStatusKeep: 'Panatilihin ang status',
    adminFindingLabel: 'Admin finding',
    adminFindingHint: 'Overall decision pagkatapos ng reviewer finding.',
    adminDecisionLabel: 'Overall decision',
    adminFindingNoteLabel: 'Note ng admin',
    adminDecisionLocked: 'Available ang overall decision kapag naipadala na ng reviewer para sa approval.',
    adminDecisionPending: 'Wala pang desisyon',
    adminFindingNoteNeeded: 'Isulat kung bakit Not Eligible. Makikita ito ng requestor.',
    accountantIssueLabel: 'Accountant issue',
    accountantIssueHint: 'Remarks at ang amount na ibibigay. I-set ito pagkatapos ng Eligible.',
    accountantIssueLocked: 'I-set ang amount pagkatapos ng Eligible.',
    accountantNoteLabel: 'Remarks',
    fundAmountLabel: 'Amount',
    fundAmountNeeded: 'I-set ang amount bago Ready for Claim.',
    findingActorEmpty: 'Wala pang naitala.',
    attentionLabel: 'Attention',
    attentionHint: 'I-mark kung espesyal, kakaiba, o kailangan ng paalala.',
    attentionMarks: {
      special: 'Espesyal',
      odd: 'Kakaiba',
      conflict: 'Kamag-anak sa desk',
      government_event: 'Government event',
    },
    findingSaved: 'Na-save ang finding.',
    saveFinding: 'I-save ang finding',
    findingNoteNeeded: 'Isulat kung bakit Not Eligible. Makikita ito ng requestor.',
    rejectLockedHint: 'Pag na-save, hindi na ma-o-override ang Not Eligible.',
    rejectConfirmTitle: 'I-save as Not Eligible?',
    rejectConfirmBody: 'Hindi na ito ma-o-override. Makikita ng requestor ang note na isinulat mo.',
    rejectConfirm: 'I-save as Not Eligible',
    rejectConfirmCancel: 'Cancel',
    claim: 'I-claim',
    open: 'Buksan',
    saveRequirements: 'I-save ang requirements',
    assignLabel: 'I-assign',
    reviewerLabel: 'Reviewer',
    accountantLabel: 'Accountant',
    assignSave: 'I-save ang assignment',
    assigned: 'Na-save ang assignment.',
    missingLabel: 'Humingi ng papeles',
    missingNoteLabel: 'Ano ang kulang',
    extraPaperLabel: 'Dagdag na papeles',
    escalateLabel: 'I-tanong sa admin',
    escalateNoteLabel: 'Bakit titignan ng admin',
    expedite: 'I-expedite',
    flagRequest: 'I-flag ang request',
    flagRequester: 'I-flag ang requestor',
    flagBeneficiary: 'I-flag ang beneficiary',
    historyLabel: 'Kasaysayan',
    report: 'Gumawa ng report',
    reportExcel: 'Excel',
    reportCsv: 'CSV',
    reportPdf: 'PDF statement',
    reportError: 'Hindi magawa ang report.',
    cooldownRule: '3-buwan na rule: may solicitation na ang taong ito.',
    relativeFlag: 'Tugma sa unang pamilya',
    suspiciousFlag: 'Kahina-hinala',
    claimHint: 'Control number, pangalan ng requester, larawan ng receive, at acknowledgement.',
    kinds: {
      burial: 'Libing',
      education: 'Educational',
      medical: 'Medical',
      events: 'Events',
      financial: 'Financial',
      daily: 'Daily',
    },
    statuses: {
      under_review: 'Pending for Review',
      pending_validation: 'For Approval',
      rejected: 'Not Eligible',
      eligible: 'Eligible',
      ready_to_claim: 'Ready for Claim',
      claimed: 'Claimed',
    },
    relations: {
      spouse: 'Asawa',
      parent: 'Magulang',
      child: 'Anak',
      sibling: 'Kapatid',
    },
  },
} as const;

export function getSolicitationCopy(locale?: AppLocale) {
  return pickCopy(copy, locale);
}
